# Generated by Django 3.1.4 on 2020-12-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0030_checkout_channel_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='vin_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
