# Generated by Django 3.1.4 on 2020-12-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0093_auto_20201130_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vin_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
