# Generated by Django 3.1.4 on 2021-03-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0094_order_vin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vin_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
