# Generated by Django 3.1.4 on 2021-05-24 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0095_auto_20210323_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('status', models.CharField(choices=[('draft_created', 'The draft order was created'), ('draft_added_products', 'Some products were added to the draft order'), ('draft_removed_products', 'Some products were removed from the draft order'), ('placed', 'The order was placed'), ('placed_from_draft', 'The draft order was placed'), ('oversold_items', 'The draft order was placed with oversold items'), ('canceled', 'The order was canceled'), ('order_marked_as_paid', 'The order was manually marked as fully paid'), ('order_fully_paid', 'The order was fully paid'), ('updated_address', 'The address from the placed order was updated'), ('email_sent', 'The email was sent'), ('confirmed', 'Order was confirmed'), ('payment_authorized', 'The payment was authorized'), ('payment_captured', 'The payment was captured'), ('external_service_notification', 'Notification from external service'), ('payment_refunded', 'The payment was refunded'), ('payment_voided', 'The payment was voided'), ('payment_failed', 'The payment was failed'), ('invoice_requested', 'An invoice was requested'), ('invoice_generated', 'An invoice was generated'), ('invoice_updated', 'An invoice was updated'), ('invoice_sent', 'An invoice was sent'), ('fulfillment_canceled', 'A fulfillment was canceled'), ('fulfillment_restocked_items', 'The items of the fulfillment were restocked'), ('fulfillment_fulfilled_items', 'Some items were fulfilled'), ('fulfillment_refunded', 'Some items were refunded'), ('tracking_updated', "The fulfillment's tracking code was updated"), ('note_added', 'A note was added to the order'), ('return_request', 'Customer requested a return'), ('confirm_return', 'Returned items was confirmed'), ('other', 'An unknown order event containing a message')], default='return_request', max_length=100)),
                ('confirmed_at', models.DateTimeField(null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='type',
            field=models.CharField(choices=[('DRAFT_CREATED', 'draft_created'), ('DRAFT_ADDED_PRODUCTS', 'draft_added_products'), ('DRAFT_REMOVED_PRODUCTS', 'draft_removed_products'), ('PLACED', 'placed'), ('PLACED_FROM_DRAFT', 'placed_from_draft'), ('OVERSOLD_ITEMS', 'oversold_items'), ('CANCELED', 'canceled'), ('ORDER_MARKED_AS_PAID', 'order_marked_as_paid'), ('ORDER_FULLY_PAID', 'order_fully_paid'), ('UPDATED_ADDRESS', 'updated_address'), ('EMAIL_SENT', 'email_sent'), ('CONFIRMED', 'confirmed'), ('PAYMENT_AUTHORIZED', 'payment_authorized'), ('PAYMENT_CAPTURED', 'payment_captured'), ('EXTERNAL_SERVICE_NOTIFICATION', 'external_service_notification'), ('PAYMENT_REFUNDED', 'payment_refunded'), ('PAYMENT_VOIDED', 'payment_voided'), ('PAYMENT_FAILED', 'payment_failed'), ('INVOICE_REQUESTED', 'invoice_requested'), ('INVOICE_GENERATED', 'invoice_generated'), ('INVOICE_UPDATED', 'invoice_updated'), ('INVOICE_SENT', 'invoice_sent'), ('FULFILLMENT_CANCELED', 'fulfillment_canceled'), ('FULFILLMENT_RESTOCKED_ITEMS', 'fulfillment_restocked_items'), ('FULFILLMENT_FULFILLED_ITEMS', 'fulfillment_fulfilled_items'), ('FULFILLMENT_REFUNDED', 'fulfillment_refunded'), ('TRACKING_UPDATED', 'tracking_updated'), ('NOTE_ADDED', 'note_added'), ('RETURN_REQUEST', 'return_request'), ('CONFIRM_RETURN', 'confirm_return'), ('OTHER', 'other')], max_length=255),
        ),
        migrations.CreateModel(
            name='OrderReturnLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_lines', to='order.orderline')),
                ('order_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_lines', to='order.orderreturn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='lines',
            field=models.ManyToManyField(related_name='lines', through='order.OrderReturnLine', to='order.OrderLine'),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='order.order'),
        ),
    ]
