# Generated by Django 3.1.4 on 2021-05-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0096_auto_20210524_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
