# Generated by Django 3.1.4 on 2020-12-24 09:44

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_address_location_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='location_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
